// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: service.proto

package typesconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	types "github.com/gokch/kioskgo/types"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// FileServiceName is the fully-qualified name of the FileService service.
	FileServiceName = "proto.FileService"
)

// FileServiceClient is a client for the proto.FileService service.
type FileServiceClient interface {
	Upload(context.Context, *connect_go.Request[types.UploadReq]) (*connect_go.Response[types.UploadResp], error)
}

// NewFileServiceClient constructs a client for the proto.FileService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFileServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) FileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &fileServiceClient{
		upload: connect_go.NewClient[types.UploadReq, types.UploadResp](
			httpClient,
			baseURL+"/proto.FileService/Upload",
			opts...,
		),
	}
}

// fileServiceClient implements FileServiceClient.
type fileServiceClient struct {
	upload *connect_go.Client[types.UploadReq, types.UploadResp]
}

// Upload calls proto.FileService.Upload.
func (c *fileServiceClient) Upload(ctx context.Context, req *connect_go.Request[types.UploadReq]) (*connect_go.Response[types.UploadResp], error) {
	return c.upload.CallUnary(ctx, req)
}

// FileServiceHandler is an implementation of the proto.FileService service.
type FileServiceHandler interface {
	Upload(context.Context, *connect_go.Request[types.UploadReq]) (*connect_go.Response[types.UploadResp], error)
}

// NewFileServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFileServiceHandler(svc FileServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/proto.FileService/Upload", connect_go.NewUnaryHandler(
		"/proto.FileService/Upload",
		svc.Upload,
		opts...,
	))
	return "/proto.FileService/", mux
}

// UnimplementedFileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFileServiceHandler struct{}

func (UnimplementedFileServiceHandler) Upload(context.Context, *connect_go.Request[types.UploadReq]) (*connect_go.Response[types.UploadResp], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.FileService.Upload is not implemented"))
}
